# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wellington/cpp/companents/TradingBasics

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wellington/cpp/companents/TradingBasics

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wellington/cpp/companents/TradingBasics/CMakeFiles /home/wellington/cpp/companents/TradingBasics/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wellington/cpp/companents/TradingBasics/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TradingBasics

# Build rule for target.
TradingBasics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TradingBasics
.PHONY : TradingBasics

# fast build rule for target.
TradingBasics/fast:
	$(MAKE) -f CMakeFiles/TradingBasics.dir/build.make CMakeFiles/TradingBasics.dir/build
.PHONY : TradingBasics/fast

src/BarPeriod.o: src/BarPeriod.cpp.o

.PHONY : src/BarPeriod.o

# target to build an object file
src/BarPeriod.cpp.o:
	$(MAKE) -f CMakeFiles/TradingBasics.dir/build.make CMakeFiles/TradingBasics.dir/src/BarPeriod.cpp.o
.PHONY : src/BarPeriod.cpp.o

src/BarPeriod.i: src/BarPeriod.cpp.i

.PHONY : src/BarPeriod.i

# target to preprocess a source file
src/BarPeriod.cpp.i:
	$(MAKE) -f CMakeFiles/TradingBasics.dir/build.make CMakeFiles/TradingBasics.dir/src/BarPeriod.cpp.i
.PHONY : src/BarPeriod.cpp.i

src/BarPeriod.s: src/BarPeriod.cpp.s

.PHONY : src/BarPeriod.s

# target to generate assembly for a file
src/BarPeriod.cpp.s:
	$(MAKE) -f CMakeFiles/TradingBasics.dir/build.make CMakeFiles/TradingBasics.dir/src/BarPeriod.cpp.s
.PHONY : src/BarPeriod.cpp.s

src/BasisOfStrategy.o: src/BasisOfStrategy.cpp.o

.PHONY : src/BasisOfStrategy.o

# target to build an object file
src/BasisOfStrategy.cpp.o:
	$(MAKE) -f CMakeFiles/TradingBasics.dir/build.make CMakeFiles/TradingBasics.dir/src/BasisOfStrategy.cpp.o
.PHONY : src/BasisOfStrategy.cpp.o

src/BasisOfStrategy.i: src/BasisOfStrategy.cpp.i

.PHONY : src/BasisOfStrategy.i

# target to preprocess a source file
src/BasisOfStrategy.cpp.i:
	$(MAKE) -f CMakeFiles/TradingBasics.dir/build.make CMakeFiles/TradingBasics.dir/src/BasisOfStrategy.cpp.i
.PHONY : src/BasisOfStrategy.cpp.i

src/BasisOfStrategy.s: src/BasisOfStrategy.cpp.s

.PHONY : src/BasisOfStrategy.s

# target to generate assembly for a file
src/BasisOfStrategy.cpp.s:
	$(MAKE) -f CMakeFiles/TradingBasics.dir/build.make CMakeFiles/TradingBasics.dir/src/BasisOfStrategy.cpp.s
.PHONY : src/BasisOfStrategy.cpp.s

src/CIndicatorES.o: src/CIndicatorES.cpp.o

.PHONY : src/CIndicatorES.o

# target to build an object file
src/CIndicatorES.cpp.o:
	$(MAKE) -f CMakeFiles/TradingBasics.dir/build.make CMakeFiles/TradingBasics.dir/src/CIndicatorES.cpp.o
.PHONY : src/CIndicatorES.cpp.o

src/CIndicatorES.i: src/CIndicatorES.cpp.i

.PHONY : src/CIndicatorES.i

# target to preprocess a source file
src/CIndicatorES.cpp.i:
	$(MAKE) -f CMakeFiles/TradingBasics.dir/build.make CMakeFiles/TradingBasics.dir/src/CIndicatorES.cpp.i
.PHONY : src/CIndicatorES.cpp.i

src/CIndicatorES.s: src/CIndicatorES.cpp.s

.PHONY : src/CIndicatorES.s

# target to generate assembly for a file
src/CIndicatorES.cpp.s:
	$(MAKE) -f CMakeFiles/TradingBasics.dir/build.make CMakeFiles/TradingBasics.dir/src/CIndicatorES.cpp.s
.PHONY : src/CIndicatorES.cpp.s

src/Forecasting.o: src/Forecasting.cpp.o

.PHONY : src/Forecasting.o

# target to build an object file
src/Forecasting.cpp.o:
	$(MAKE) -f CMakeFiles/TradingBasics.dir/build.make CMakeFiles/TradingBasics.dir/src/Forecasting.cpp.o
.PHONY : src/Forecasting.cpp.o

src/Forecasting.i: src/Forecasting.cpp.i

.PHONY : src/Forecasting.i

# target to preprocess a source file
src/Forecasting.cpp.i:
	$(MAKE) -f CMakeFiles/TradingBasics.dir/build.make CMakeFiles/TradingBasics.dir/src/Forecasting.cpp.i
.PHONY : src/Forecasting.cpp.i

src/Forecasting.s: src/Forecasting.cpp.s

.PHONY : src/Forecasting.s

# target to generate assembly for a file
src/Forecasting.cpp.s:
	$(MAKE) -f CMakeFiles/TradingBasics.dir/build.make CMakeFiles/TradingBasics.dir/src/Forecasting.cpp.s
.PHONY : src/Forecasting.cpp.s

src/Indicators.o: src/Indicators.cpp.o

.PHONY : src/Indicators.o

# target to build an object file
src/Indicators.cpp.o:
	$(MAKE) -f CMakeFiles/TradingBasics.dir/build.make CMakeFiles/TradingBasics.dir/src/Indicators.cpp.o
.PHONY : src/Indicators.cpp.o

src/Indicators.i: src/Indicators.cpp.i

.PHONY : src/Indicators.i

# target to preprocess a source file
src/Indicators.cpp.i:
	$(MAKE) -f CMakeFiles/TradingBasics.dir/build.make CMakeFiles/TradingBasics.dir/src/Indicators.cpp.i
.PHONY : src/Indicators.cpp.i

src/Indicators.s: src/Indicators.cpp.s

.PHONY : src/Indicators.s

# target to generate assembly for a file
src/Indicators.cpp.s:
	$(MAKE) -f CMakeFiles/TradingBasics.dir/build.make CMakeFiles/TradingBasics.dir/src/Indicators.cpp.s
.PHONY : src/Indicators.cpp.s

src/PnlAction.o: src/PnlAction.cpp.o

.PHONY : src/PnlAction.o

# target to build an object file
src/PnlAction.cpp.o:
	$(MAKE) -f CMakeFiles/TradingBasics.dir/build.make CMakeFiles/TradingBasics.dir/src/PnlAction.cpp.o
.PHONY : src/PnlAction.cpp.o

src/PnlAction.i: src/PnlAction.cpp.i

.PHONY : src/PnlAction.i

# target to preprocess a source file
src/PnlAction.cpp.i:
	$(MAKE) -f CMakeFiles/TradingBasics.dir/build.make CMakeFiles/TradingBasics.dir/src/PnlAction.cpp.i
.PHONY : src/PnlAction.cpp.i

src/PnlAction.s: src/PnlAction.cpp.s

.PHONY : src/PnlAction.s

# target to generate assembly for a file
src/PnlAction.cpp.s:
	$(MAKE) -f CMakeFiles/TradingBasics.dir/build.make CMakeFiles/TradingBasics.dir/src/PnlAction.cpp.s
.PHONY : src/PnlAction.cpp.s

src/PowellsMethod.o: src/PowellsMethod.cpp.o

.PHONY : src/PowellsMethod.o

# target to build an object file
src/PowellsMethod.cpp.o:
	$(MAKE) -f CMakeFiles/TradingBasics.dir/build.make CMakeFiles/TradingBasics.dir/src/PowellsMethod.cpp.o
.PHONY : src/PowellsMethod.cpp.o

src/PowellsMethod.i: src/PowellsMethod.cpp.i

.PHONY : src/PowellsMethod.i

# target to preprocess a source file
src/PowellsMethod.cpp.i:
	$(MAKE) -f CMakeFiles/TradingBasics.dir/build.make CMakeFiles/TradingBasics.dir/src/PowellsMethod.cpp.i
.PHONY : src/PowellsMethod.cpp.i

src/PowellsMethod.s: src/PowellsMethod.cpp.s

.PHONY : src/PowellsMethod.s

# target to generate assembly for a file
src/PowellsMethod.cpp.s:
	$(MAKE) -f CMakeFiles/TradingBasics.dir/build.make CMakeFiles/TradingBasics.dir/src/PowellsMethod.cpp.s
.PHONY : src/PowellsMethod.cpp.s

src/Prices.o: src/Prices.cpp.o

.PHONY : src/Prices.o

# target to build an object file
src/Prices.cpp.o:
	$(MAKE) -f CMakeFiles/TradingBasics.dir/build.make CMakeFiles/TradingBasics.dir/src/Prices.cpp.o
.PHONY : src/Prices.cpp.o

src/Prices.i: src/Prices.cpp.i

.PHONY : src/Prices.i

# target to preprocess a source file
src/Prices.cpp.i:
	$(MAKE) -f CMakeFiles/TradingBasics.dir/build.make CMakeFiles/TradingBasics.dir/src/Prices.cpp.i
.PHONY : src/Prices.cpp.i

src/Prices.s: src/Prices.cpp.s

.PHONY : src/Prices.s

# target to generate assembly for a file
src/Prices.cpp.s:
	$(MAKE) -f CMakeFiles/TradingBasics.dir/build.make CMakeFiles/TradingBasics.dir/src/Prices.cpp.s
.PHONY : src/Prices.cpp.s

src/StringHasher.o: src/StringHasher.cpp.o

.PHONY : src/StringHasher.o

# target to build an object file
src/StringHasher.cpp.o:
	$(MAKE) -f CMakeFiles/TradingBasics.dir/build.make CMakeFiles/TradingBasics.dir/src/StringHasher.cpp.o
.PHONY : src/StringHasher.cpp.o

src/StringHasher.i: src/StringHasher.cpp.i

.PHONY : src/StringHasher.i

# target to preprocess a source file
src/StringHasher.cpp.i:
	$(MAKE) -f CMakeFiles/TradingBasics.dir/build.make CMakeFiles/TradingBasics.dir/src/StringHasher.cpp.i
.PHONY : src/StringHasher.cpp.i

src/StringHasher.s: src/StringHasher.cpp.s

.PHONY : src/StringHasher.s

# target to generate assembly for a file
src/StringHasher.cpp.s:
	$(MAKE) -f CMakeFiles/TradingBasics.dir/build.make CMakeFiles/TradingBasics.dir/src/StringHasher.cpp.s
.PHONY : src/StringHasher.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... TradingBasics"
	@echo "... test"
	@echo "... src/BarPeriod.o"
	@echo "... src/BarPeriod.i"
	@echo "... src/BarPeriod.s"
	@echo "... src/BasisOfStrategy.o"
	@echo "... src/BasisOfStrategy.i"
	@echo "... src/BasisOfStrategy.s"
	@echo "... src/CIndicatorES.o"
	@echo "... src/CIndicatorES.i"
	@echo "... src/CIndicatorES.s"
	@echo "... src/Forecasting.o"
	@echo "... src/Forecasting.i"
	@echo "... src/Forecasting.s"
	@echo "... src/Indicators.o"
	@echo "... src/Indicators.i"
	@echo "... src/Indicators.s"
	@echo "... src/PnlAction.o"
	@echo "... src/PnlAction.i"
	@echo "... src/PnlAction.s"
	@echo "... src/PowellsMethod.o"
	@echo "... src/PowellsMethod.i"
	@echo "... src/PowellsMethod.s"
	@echo "... src/Prices.o"
	@echo "... src/Prices.i"
	@echo "... src/Prices.s"
	@echo "... src/StringHasher.o"
	@echo "... src/StringHasher.i"
	@echo "... src/StringHasher.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

